version: "3.4"

services:

  scenedetection:
    container_name: "scenedetection"
    image: classtranscribe/ct-python:staging
    build:
      context: ..
    volumes:
      - "${DATA:-~/docker_data}/data:/data"
    networks:
      - classtranscribe
    environment:
      PYTHONUNBUFFERED: "1"
      RABBITMQ_URI: "amqp://guest:guest@rabbitmq:5672/%2f"
      DOWNLOAD_MISSING_VIDEOS: "true"
      RABBITMQ_QUEUENAME: 'SceneDetection'
      SCENE_DETECT_ALGORITHM_CLASS: "SvmPoly2"
      SCENE_DETECT_ALGORITHM_MODULE: "pkg.agent.tasks.lib.scenedetection.svm_poly2"
    depends_on:
      - rabbitmq


  phrasehinter:
    container_name: "phrasehinter"
    image: classtranscribe/ct-python:staging
    build:
      context: ..
    volumes:
      - "${DATA:-~/docker_data}/data:/data"
    networks:
      - classtranscribe
    environment:
      PYTHONUNBUFFERED: "1"
      RABBITMQ_URI: "amqp://guest:guest@rabbitmq:5672/%2f"
      DOWNLOAD_MISSING_VIDEOS: "true"
      RABBITMQ_QUEUENAME: 'PhraseHinter'
    depends_on:
      - rabbitmq


networks:
  classtranscribe:
