version: "3.4"

services:

  scenedetection:
    image: classtranscribe/ct-python
    build:
      context: ..
    volumes:
      - "${DATA:-~/docker_data}/data:/data"
    environment:
      RABBITMQ_URI: 'amqp://guest:guest@rabbitmq:5672/%2f'
      RABBITMQ_EXCHANGE: ""
      DEBUG: "true"
      DATA_DIRECTORY: "/data"
      DOWNLOAD_MISSING_VIDEOS: "true"
      READONLY: "true"
      RABBITMQ_QUEUENAME: 'SceneDetection'
      SCENE_DETECT_ALGORITHM_CLASS: "SimStructuralV1"
      SCENE_DETECT_ALGORITHM_MODULE: "pkg.agent.tasks.lib.scenedetection.sim_structural"
    depends_on:
      - rabbitmq

  phrasehinter:
    image: classtranscribe/ct-python
    build:
      context: ..
    volumes:
      - "${DATA:-~/docker_data}/data:/data"
    environment:
      RABBITMQ_URI: 'amqp://guest:guest@rabbitmq:5672/%2f'
      RABBITMQ_EXCHANGE: ""
      DEBUG: "true"
      DATA_DIRECTORY: "/data"
      DOWNLOAD_MISSING_VIDEOS: "true"
      RABBITMQ_QUEUENAME: 'PhraseHinter'
      READONLY: "true"
    depends_on:
      - rabbitmq
